USE ClinicaEspecialidadV1
SELECT * FROM Cita
SELECT * FROM Consultorio
SELECT * FROM DetalleReceta
SELECT * FROM DetalleVenta
SELECT * FROM  Empleado
SELECT * FROM Especialidad
SELECT * FROM Factura
SELECT * FROM Medicamento
SELECT * FROM Medico
SELECT * FROM Paciente
SELECT * FROM Pago
SELECT * FROM Recepcionista
SELECT * FROM Receta
SELECT * FROM Servicio
SELECT * FROM TipoEmpleado
SELECT * FROM TipoUsuario
SELECT * FROM Venta
SELECT * FROM Usuario
